name: OTP CI Build
# On [push, pull_request] causes double-builds when creating PRs.
# But triggering on push only will miss pull requests from outside authors.
# The push event's ref is the name of the pushed branch;
# The pull_request event's branch name is the merge target branch.
on:
  push:
    branches:
      - master
      - dev-1.x
      - dev-2.x
  pull_request:
    branches:
      - master
      - dev-1.x
      - dev-2.x
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Starting in v2.2 checkout action fetches all tags when fetch-depth=0, for auto-versioning.
      - uses: actions/checkout@v2.3.2
        with:
          fetch-depth: 0
      # Java setup step completes very fast, no need to run in a preconfigured docker container
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # on windows there are frequent failures caused by page files being too small
      # https://github.com/actions/virtual-environments/issues/785
      - name: Configure Windows Pagefile
        if: matrix.os == 'windows-latest'
        uses: al-cheb/configure-pagefile-action@v1.2

      - name: Prepare coverage agent, build and test
        run: mvn --batch-mode --update-snapshots jacoco:prepare-agent verify jacoco:report -P prettierCheck

      - name: Send coverage data to codecov.io
        if: github.repository_owner == 'opentripplanner'
        uses: codecov/codecov-action@v2
        with:
          files: target/site/jacoco/jacoco.xml

      - name: Sets env vars for release
        if: ${{ github.repository_owner == 'mfdz' && github.ref == 'refs/heads/dev-2.x' }}
        run: echo "DOCKER_DATE_TAG=`date +%Y-%m-%d-%H_%M`" >> $GITHUB_ENV
        env:
          TZ: Europe/Berlin

      - name: Publish to Dockerhub
        if: ${{ github.repository_owner == 'mfdz' && github.ref == 'refs/heads/dev-2.x' }}
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: mfdz/opentripplanner
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_AUTH}}
          tags: "latest,${{ github.sha }},${{ env.DOCKER_DATE_TAG }}"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  container-image:
    if: github.repository_owner == 'opentripplanner' && github.event_name == 'push' && github.ref == 'refs/heads/dev-2.x'
    runs-on: ubuntu-latest
    needs: build
    env:
      CONTAINER_REPO: docker.io/opentripplanner/opentripplanner
      CONTAINER_REGISTRY_USER: otpbot
      CONTAINER_REGISTRY_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
    steps:
      - uses: actions/checkout@v2.3.2
        with:
          fetch-depth: 0
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build container image with Jib, push to Dockerhub
        run: mvn --batch-mode compile com.google.cloud.tools:jib-maven-plugin:build -Djib.to.tags=latest,${{ github.sha }}
